docs: fix shell prompt rendering
In the published guide, the escaping backslashes on terminal prompts
(`\$`) were rendering. Updated to the latest mdbook deps locally
(to match what's installed in CI) and was able to reproduce the problem.
Added a config tweak to the book.toml to suppress:

   Error: The katex preprocessor does not support the 'katex' renderer

Now working well.