fix(pcli): require deposit when submitting proposal
The `--deposit-amount` flag is required when running `pcli tx proposal
submit`, but the clap settings weren't enforcing that, and the resulting
error message was quite vague. Now, running `pcli tx proposal submit`
without providing a `--deposit-amount` flag emits a helpful error
message:

  error: The following required arguments were not provided:
      --deposit-amount <DEPOSIT_AMOUNT>

The parsing the amount, e.g. "10penumbra", remains unchanged.

Closes #3455.