test(pindexer): add integration tests to validate db contents
Adds some feature-gated integration tests, not yet hooked up to CI,
to sanity check that the ABCI events pipeline is working:

  pd -> cometbft -> postgres -> pindexer

The integration tests talk to local postgres databases and make
assertions about their contents. There's also a small change to the
process-compose orchestration, instructing pindexer to wait for the
fullnode services to come up, lest it error out early due to an empty
database. The error I observed on an empty db was:

  Error: error occurred while decoding column 0: unexpected null;
  try decoding as an `Option`
  Caused by:
    unexpected null; try decoding as an `Option`

Which is distinct from the error reported in #4999. By waiting
a bit longer we can ensure a clean start even on a fresh devnet.

Will follow up with subsequent PRs to make sure these tests run in CI.