pcli: try to support HTTPS URLs
I haven't got this working against https://grpc.testnet.penumbra.zone, which fails with
```
Error: status: Internal, message: "grpc-status header missing, mapped from HTTP status code 400", details: [], metadata: MetadataMap { headers: {"content-length": "0", "date": "Sat, 08 Apr 2023 21:51:34 GMT", "via": "1.1 google", "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"} }
```
but I think this isn't a problem with the `pcli` support, so this could be good
to merge anyways (but not yet advertise).  Once we can get HTTPS working with
grpc.testnet.penumbra.zone, we can switch the default endpoint over.