build: bump rust to 1.83
cherry picked from commit 5717176912b0b4ae60bd037c04ab06c51b6827ab,
then bumped 1.80 -> 1.83. Also includes a `nix flake update` so that
rust 1.83 is available. Doing this on a backport branch, so that CI
passes against the `v0.80.x` code. This is necessary because the
docs-lint dependencies aren't pinned, but should be.

A few other fix-it commits were squashed into this one:

lint: allow dead code in test modules

lint: cargo fmt

chore: bump proptest derive

Required for getting `cargo check` to pass, errors were

error: non-local `impl` definition, `impl` blocks should be written at the same level as their item
  --> crates/crypto/tct/src/epoch.rs:79:53
   |
79 | #[cfg_attr(any(test, feature = "arbitrary"), derive(proptest_derive::Arbitrary))]
   |                                                     ^-------------------------
   |                                                     |
   |                                                     `Arbitrary` is not local
   |                                                     move the `impl` block outside of this constant `_IMPL_ARBITRARY_FOR_Root`
80 | pub struct Root(pub Hash);
   |            ---- `Root` is not local

build: bump rust to 1.83

cherry picked from commit 5717176912b0b4ae60bd037c04ab06c51b6827ab,
then bumped 1.80 -> 1.83. Also includes a `nix flake update` so that
rust 1.83 is available. Doing this on a backport branch, so that CI
passes against the `v0.80.x` code. This is necessary because the
docs-lint dependencies aren't pinned, but should be.

A few other fix-it commits were squashed into this one:

lint: allow dead code in test modules

lint: cargo fmt

chore: bump proptest derive

Required for getting `cargo check` to pass, errors were

error: non-local `impl` definition, `impl` blocks should be written at the same level as their item
  --> crates/crypto/tct/src/epoch.rs:79:53
   |
79 | #[cfg_attr(any(test, feature = "arbitrary"), derive(proptest_derive::Arbitrary))]
   |                                                     ^-------------------------
   |                                                     |
   |                                                     `Arbitrary` is not local
   |                                                     move the `impl` block outside of this constant `_IMPL_ARBITRARY_FOR_Root`
80 | pub struct Root(pub Hash);
   |            ---- `Root` is not local